### ISSUE TITLE
Support Non-Nullability

### ISSUE THREAD

**Issue by kostaa** [wrike/re-reselect#1]
Is this library still maintained?
Any plans for Non-Nullability?

**Comment by missvalentinep** [comment]
@kostaa yes! We will start working on adding nnbd now

**Comment by kostaa** [comment]
Thanks for letting me know.
Do you have an ETA?

**Comment by missvalentinep** [comment]
@kostaa I'm planning to get it done by Tuesday.

**Comment by missvalentinep** [comment]
@kostaa although, I'm starting to look at the code, and it might take a bit more time.

As I can see, we need the reselect package to support nnbd. I've seen a PR - https://github.com/brianegan/reselect_dart/pull/9 - and it requires memoize_dart to support nnbd. As you can see, the request mentioned there has been merged, but we're having a small trouble with uploading the new version to pub.dev, and resolving it may take a couple of days.

I appreciate the fact that you're using our packages and your input in helping to improve them! Getting them to work is a top priority for me now.

**Comment by kostaa** [comment]
Hi @missvalentinep
I can see that you have a pull request for this upgrade. 
Do you have an ETA for this to be published?

**Comment by missvalentinep** [comment]
@kostaa the package has been published, thanks for the ping!

**Comment by kostaa** [comment]
Thanks for that much appreciated.
